.PHONY: clean All

All:
	@echo "----------Building project:[ day_4 - Debug ]----------"
	@cd "day_4" && "$(MAKE)" -f  "day_4.mk"
clean:
	@echo "----------Cleaning project:[ day_4 - Debug ]----------"
	@cd "day_4" && "$(MAKE)" -f  "day_4.mk" clean
