.PHONY: clean All

All:
	@echo "----------Building project:[ day_1 - Debug ]----------"
	@cd "day_1" && "$(MAKE)" -f  "day_1.mk"
clean:
	@echo "----------Cleaning project:[ day_1 - Debug ]----------"
	@cd "day_1" && "$(MAKE)" -f  "day_1.mk" clean
