.PHONY: clean All

All:
	@echo "----------Building project:[ day_5 - Debug ]----------"
	@cd "day_5" && "$(MAKE)" -f  "day_5.mk"
clean:
	@echo "----------Cleaning project:[ day_5 - Debug ]----------"
	@cd "day_5" && "$(MAKE)" -f  "day_5.mk" clean
